@host = http://127.0.0.1:3004


### /oauth/request_token
GET {{host}}/oauth/request_token



### /oauth/authenticate
GET {{host}}/oauth/authenticate
    ?oauth_token=



### /oauth/access_token
GET {{host}}/oauth/access_token
    ?oauth_token=8rGIdgAAAAABsz_iAAABjmwkmEE
    &oauth_verifier=v9z7wCfu2ZE7BFGwPmfVD2sJZwCzL2PI



### /account/verify_credentials
GET {{host}}/account/verify_credentials
    ?token=
    &token_secret=




### /authentication/x-auth-token
GET {{host}}/authentication/x-auth-token



### /authentication/through-verify-get-x-user
GET {{host}}/authentication/through-verify-get-x-user
    ?oauth_token=7JIb3wAAAAABsz_iAAABjmw7yOY
    &oauth_verifier=RZmq3eWrOpCegJ4bmFJ8DdZjw0gIY69i