@host = http://127.0.0.1:3004


### /oauth/request_token
GET {{host}}/oauth/request_token



### /oauth/authenticate
GET {{host}}/oauth/authenticate
    ?oauth_token=



### /oauth/access_token
GET {{host}}/oauth/access_token
    ?oauth_token=
    &oauth_verifier=


### /authentication/x-auth-token
GET {{host}}/authentication/x-auth-token



### /authentication/through-verify-get-x-user
GET {{host}}/authentication/through-verify-get-x-user
    ?oauth_token=
    &oauth_verifier=